### ISSUE TITLE
No issue, just questions!

### ISSUE THREAD

**Issue by Naesstrom** [Ceerbeerus/beerbolaget#1]
So I got really interested when I saw this component since I was already running untappd 🍻 

I've installed it and it seems to be working, no release this week etc. but can I somehow show the json data prettier? I was hoping to get some kind of table showing each beer with images, ratings etc.

Oh and regarding images, what should I use at `image_url`? I tried using `https://static.systembolaget.se/imagelibrary/publishedmedia/` but that doesn't seem to generate any images!

![image](https://user-images.githubusercontent.com/6575206/63795803-05276c80-c905-11e9-8431-0a3f94154b3b.png)

**Comment by Naesstrom** [comment]
My bad, just found the custom card and asked about the URL in the forum instead!

**Comment by Ceerbeerus** [comment]
Sorry for the late respons. I’m glad you got it working. The URL is in the options table now.
