### ISSUE TITLE
I/O inside the event loop

### ISSUE THREAD

**Issue by kenvase** [Ceerbeerus/beerbolaget#10]
Get this in the HA log:

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for beerbolaget doing I/O at custom_components/beerbolaget/__init__.py, line 107: await self.beer_handle.get_store_info()

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for beerbolaget doing I/O at custom_components/beerbolaget/__init__.py, line 110: await self.beer_handle.update_new_beers()

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for beerbolaget doing I/O at custom_components/beerbolaget/__init__.py, line 116: await self.beer_handle.get_images()

**Comment by Ceerbeerus** [comment]
Thanks, I saw that last night too.
I'll see if I can get that fixed together with the release of untappd auth-flow tonight.

**Comment by Ceerbeerus** [comment]
Fixed as of 0.4.0.
Please note the breaking changes.
