### ISSUE TITLE
Testing the auth-flow integrated release 0.4.0 - almost a susses 

### ISSUE THREAD

**Issue by JonasStenmarck** [Ceerbeerus/beerbolaget#11]
Changed config according to the readme. 
Did get the configurator notification. Klicked the link for authorization of the app (Untapped site). Worked fine. Ended upp with a request in a new browser window with my callback URL and session token (URL?code=nnnnnnnnnnnnnnnnnn...). 

Went back to the ha page and clicked the "I AUTHORIZED SUCCESSFULLY" button. 
Nothing happened. When reloading the ha page one more configurator notification appears.

Noticed a difference from the example: my callback (ha site) use https, don't know that matters.

**Comment by Ceerbeerus** [comment]
Can you paste your configuration.yaml?
Is there any .untappd-token-cache file present in your folder?
Anything in the log?

**Comment by JonasStenmarck** [comment]
configuration.yaml:

`beerbolaget:`
`    api_key: !secret systembolaget_api`
`    image_url: "https://www.systembolaget.se/api/productsearch/search/sok-dryck"`
`    store: "PK-Huset"`
`    untappd_client_id: !secret untappd_client`
`    untappd_secret: !secret untappd_secret`
`    untappd_callback: https://ha.NNNNN.com/api/untappd`

No .untappd-token-cache and nothing in the log. 

Tried from different browser, same thing

**Comment by Ceerbeerus** [comment]
Does the callback URL in the browser match your URL for HA. i.e. the new browser window is showing your HA webgui?

**Comment by JonasStenmarck** [comment]
Yes it matches, but no html is generated only a blank page:
https://ha.NNNNN.com/api/untappd?code=4B654AA3ANNNNNNNNNNNNNNNNN

Could I use the code for testing in some way? like generate the .untappd-token-cache file.

**Comment by Ceerbeerus** [comment]
Could you try updating to 0.4.4 and check the log? 

Does HA have correct permission to be able to write to the config folder?

**Comment by JonasStenmarck** [comment]
Sure hang on!

**Comment by JonasStenmarck** [comment]
Now i get something in the log:
2020-05-05 22:31:43 ERROR (SyncWorker_12) [custom_components.beerbolaget] Error caching token. 

The user that runs HA owns the config dir and has write rights

**Comment by Ceerbeerus** [comment]
That error message indicates either, that HA can’t write the file to your folder or that untappd doesn’t respond to your request with the token.

**Comment by Naesstrom** [comment]
I'm also having a problem with the config-flow.
When I click the link I get a error message:
`{"meta":{"http_code":500,"error_type":"param_error","error_detail":"Your redirect_url is invalid or doesn't match what was provided in registration"},"response":[]}`
and the URL shown is:
`https://untappd.com/oauth/authenticate/?client_id=748A65063998C3477B76CDAAA168E7729628F166&response_type=code&redirect_url=https%3A%2F%2Fdomain.duckdns.org%3A8123%2Fapi%2Funtappd`

Config looks like this:
```
beerbolaget:
  api_key: !secret systembolaget
  image_url: "https://www.systembolaget.se/api/productsearch/search/sok-dryck"
  store: "Samarkand"
  untappd_client_id: !secret untappd_ID
  untappd_secret: !secret untappd_Secret
#  untappd_token: !secret untappd_Token
  untappd_callback: !secret untappd_callback
```
and secret callback url is:
`untappd_callback: https://domain.duckdns.org:8123/api/untappd`

**Comment by Ceerbeerus** [comment]
How does the callback URL look that you have provided to untappd when you got the api key?

The error message is from untappd and says it doesn’t match.

**Comment by Naesstrom** [comment]
Ah my bad, I used the old url without the api/untappd part, works fine now I think!

**Comment by JonasStenmarck** [comment]
Sorry for not following up last time - struggled until I fell asleep :)
Untappd responds after klickning the authentication link with the URL:
https://ha.stenmarck.com/api/untappd?code=3F4BD7F0A3742XXXXXXXXXXXXXXX 
as soon as the URL is loaded in a browser or even if copied and used with curl I get the same log entry as before: 2020-05-08 15:55:27 ERROR (SyncWorker_8) [custom_components.beerbolaget] Error caching token.
So I believe that the file cant be written. Don't get it I think it has all rights it can have. we are talking about the .untappd-token-cache right?

Can I create the file myself from the URL reponse, just for trying if it works?

**Comment by Ceerbeerus** [comment]
Yea, it’s the .untappd-token-cache file.
If the file doesn’t contain the token it will try to overwrite it with a token, i.e without correct permissions it will fail.

Try to give all users permission to write in the config folder temporary just to check if that works.

**Comment by JonasStenmarck** [comment]
I sure tried to give 777 to the config folder. Also tried to generate an empty .untappd-token-cache file with 777 rights - same thing. I don't get it. Its like its not trying. 

What should be wiritten?

**Comment by Ceerbeerus** [comment]
How does your setup look?

Hassio?
Docker?
Proxy?

**Comment by JonasStenmarck** [comment]
hassbian (on Linux)
nginx proyx (running in a docker)

And maybe there is the answer - maybe have to fiddle with the cgi folder config in nginx.
but it sure does some thing...
 I could try changing the URL and run it directly to the ha host.

**Comment by Ceerbeerus** [comment]
I have something you could try first.
I’ve sent you a message on fb, i think.
