### ISSUE TITLE
Integration not found

### ISSUE THREAD

**Issue by f0xenSWE** [Ceerbeerus/beerbolaget#13]
I installed the integration from HACS and restarted Home Assistant. 
But, the integration is not found in Home Assistant --> Configuration --> Integrations. 

Did I miss something or is there something else that I need to do to get this to work?

**Comment by Ceerbeerus** [comment]
Sorry for late response, but sadly Systembolaget has locked their API, which renders this integration useless.

**Comment by f0xenSWE** [comment]
Oh, I see.
Thats a shame, seems like a really cool integration otherwise.
