### ISSUE TITLE
Suggestion: Add a class for availability

### ISSUE THREAD

**Issue by Arronoro** [Ceerbeerus/beerbolaget#5]
A suggestion to add availability, and unavailable as a class so it is possible to change color through CSS and card-mod. I would like the text "Tillgänglig" and  "Ej Tillgänglig" to change color, not the selected store itself.

**Comment by Ceerbeerus** [comment]
This option will be added shortly.

**Comment by Ceerbeerus** [comment]
This is now implemented, but of course in https://github.com/Ceerbeerus/beerbolaget-card
