### ISSUE TITLE
Automations not working?

### ISSUE THREAD

**Issue by oskarax** [Ceerbeerus/beerbolaget#8]
There is automation example but it doesn’t work. If I look at the sensor it is always on “true”

The example says from false to true. I’ve tried to do it the other way around but still never get any notification.

How is it supposed to be set up correctly?

**Comment by Ceerbeerus** [comment]
The sensor state is false weeks where there is no new release.

If setup as in the example you’ll get a notification on monday if there is a release friday the same week.

**Comment by oskarax** [comment]
I see!

Will try again then.

So the sensor reports only if there is coming a new release?

I’ve always wondered how the sensor is supposed to work

/ Oskar

Skickat från min iPhone

**Comment by Ceerbeerus** [comment]
This week seems to be the second week in a row with a release. Meaning the automation would not be triggered. I’ll address this in the upcoming release of the component.

**Comment by oskarax** [comment]
I see. No worries.

I really like your Beerbolaget integration and hope to see it develop over time. Looking forward to ratebeer.

Skickat från min iPhone

**Comment by Ceerbeerus** [comment]
Fixed in 0.3.16
